version: "3.3"
services:
  geras_database:
    image: postgres:16.0-alpine3.17
    container_name: geras_database
    ports:
      - ${DB_PORT}:5432
    volumes:
      - geras-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  geras-db-volume:
    name: geras-db-volume
